networks:
  everything:

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ops/postgres/cfg/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=password
    networks:
      - "everything"
  # guest : guest
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rmq-data:/var/lib/rabbitmq
    networks:
      - "everything"
    environment:
      - RABBITMQ_ERLANG_COOKIE=COOKIE
volumes:
  db-data:
  rmq-data:
