version: "3.7"

networks:
  everything:

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ops/postgres/cfg/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=password
    networks:
      - "everything"
volumes:
  db-data:
