import styles from "../../styles/Home.module.css";
import Head from "next/head";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import {HubConnection} from "@microsoft/signalr";
import * as signalR from "@microsoft/signalr";
import {useHub} from "../../lib/useHub";
import {useClientMethod} from "../../lib/useClientMethod";
import ScreenSelector from "../../components/ScreenSelector";
import {useHubMethod} from "../../lib/useHubMethod";
import ConnectionState from "../../components/ConnectionState";


export default function Product() {
    const router = useRouter()
    const [connection, setConnection] = useState<HubConnection>();
    const [display, setDisplay] = useState("1")


    useEffect(() => {
        const conn = new signalR.HubConnectionBuilder()
            .withUrl(`http://localhost:3001/chatHub`)
            // .withAutomaticReconnect()
            .build();
        setConnection(conn)
    }, [])
    const { hubConnectionState, error } = useHub(connection)
    useClientMethod(connection, 'Navigate', (url) => {
        router.push(url)
    });
    const { invoke: joinRoom, loading, error: e } = useHubMethod(connection, 'JoinScreen')

    // TODO: how to auto join a room?
    // TODO: How do I know if I'm in that room?
    useEffect(() =>{
        joinRoom(display)
    }, [display, hubConnectionState])

    const onDisplayChange = (id: string) => {
        setDisplay(id)
    }

    const id = router.query.id
    return <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div>
            <ConnectionState state={hubConnectionState} />
            <ScreenSelector display={display} onChange={onDisplayChange} />

            Product: {id}
        </div>
    </div>
}
