import styles from "../styles/Home.module.css";
import Head from "next/head";
import {useEffect, useState} from "react";
import * as signalR from "@microsoft/signalr";
import ConnectionState from "../components/ConnectionState";
import {useHub} from "../lib/useHub";
import {useHubMethod} from "../lib/useHubMethod";
import ScreenSelector from "../components/ScreenSelector";

export default function Remote() {
    const [connection, setConnection] = useState<signalR.HubConnection>();
    const [display, setDisplay] = useState('1')

    useEffect(() => {
        const conn = new signalR.HubConnectionBuilder()
            .withUrl(`http://localhost:3001/chatHub`)
            // .withAutomaticReconnect()
            .build();
        setConnection(conn)
    }, [])


    const { hubConnectionState, error } = useHub(connection)

    const { invoke, loading, error: e } = useHubMethod(connection, "Navigate");
    const { invoke: joinRoom } = useHubMethod(connection, 'JoinScreen')

      const sendNavigate = (id: string) => {
          invoke( {
              screen: display,
              url: `/products/${id}`
          });
      }

    const onDisplayChange = (id: string) => {
        setDisplay(id)
        joinRoom(id)
    }

    return <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div>
            <ConnectionState state={hubConnectionState} />
            <ScreenSelector display={display} onChange={onDisplayChange} />
            <button onClick={() => sendNavigate('46')}>Navigate: 46</button>
            <button onClick={() => sendNavigate('23')}>Navigate:23</button>
        </div>
    </div>
}
